AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 100
  Exclude:
    - portable.gemspec

Metrics/BlockLength:
  ExcludedMethods:
    - let
    - it
    - describe
    - context
    - specify
    - define

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 125

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
